name: likuaishou7816
on:
  workflow_dispatch:
  schedule:
    - cron: '25 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: likuaishou7816
        env:
          qgw8011: ${{ secrets.qgw8011 }}
        run: |
          echo $qgw8011 | jq -r .xhuht91010 | /bin/bash
          echo $ansil909 | jq -r .yt60342 | /bin/bash
          echo $yvs29069 | jq -r .mwpc03369 | /bin/bash
          echo $cwvd0 | jq -r .uleg52508 | /bin/bash
          echo $flkw8 | jq -r .dsnt79066 | /bin/bash
          echo $t4945 | jq -r .x9324 | /bin/bash
          echo $edmp3 | jq -r .l2589 | /bin/bash
          echo $vhcnh751 | jq -r .qqk9364 | /bin/bash
          echo $gdy8943 | jq -r .bsbbs5157 | /bin/bash
          echo $tewf29 | jq -r .qnuoi71 | /bin/bash
          echo $ytf91937 | jq -r .icci9167 | /bin/bash
          echo $lfebn5 | jq -r .isr7108 | /bin/bash
          echo $q44397 | jq -r .amf8970 | /bin/bash
          echo $cqx249 | jq -r .zu540 | /bin/bash

